baseURL = "/"
languageCode = "en-ie"
title = "Babelish"
linkTitle = "Home"
theme = "docsy"

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentUseClassic = false
pygmentsStyle = "friendly"

enableGitInfo = true

[build]
  writeStats = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Goldmark

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
        [markup.goldmark.extensions]
              definitionList = true
              footnote = true
              linkify = true
              strikethrough = true
              table = true
              taskList = true
              typographer = true


#
[frontmatter]

lastmod = [":fileModTime", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", ":filename", "date", ":fileModTime"]
date = ["publishDate", ":filename", "date", ":fileModTime"]

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
section = [ "HTML", "print" ]

# Site parameters

[params]

time_format_blog = "2 January 2006"
time_format_default = " 2 January 2006"

titleCaseStyle = "Chicago"

github_project_repo = "https://github.com/nauvane/babelish"

# gcs_engine_id = "b3dee438472820b40"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable local search
offlineSearch = true 

# User interface configuration

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = true

[params.ui.feedback]
enable = false

[[params.links.developer]]
    	name = "GitHub: source code"
    	url = "https://github.com/nauvane/babelish"
    	icon = "fab fa-github"
        desc = "Source code for Babelish"
